services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: iot-user
      DOCKER_INFLUXDB_INIT_PASSWORD: iot-password-change-me
      DOCKER_INFLUXDB_INIT_ORG: iot-lab
      DOCKER_INFLUXDB_INIT_BUCKET: iot_raw
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: iot-lab-token-123456
    volumes:
      - influxdb_data:/var/lib/influxdb2
    healthcheck:
      test: ["CMD", "influx", "ping", "--host", "http://localhost:8086"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    restart: unless-stopped

  collector:
    build: ./collector
    depends_on:
      mosquitto:
        condition: service_started
      influxdb:
        condition: service_healthy
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      MQTT_TOPIC: iot/bai2/esp32/telemetry
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: iot-lab-token-123456
      INFLUX_ORG: iot-lab
      INFLUX_BUCKET: iot_raw
    restart: unless-stopped

  preprocess:
    build: ./preprocess
    profiles:
      - tools
    depends_on:
      influxdb:
        condition: service_healthy
    environment:
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: iot-lab-token-123456
      INFLUX_ORG: iot-lab
      INFLUX_BUCKET: iot_raw

  dashboard:
    build: ./dashboard
    depends_on:
      influxdb:
        condition: service_healthy
    environment:
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: iot-lab-token-123456
      INFLUX_ORG: iot-lab
      INFLUX_BUCKET: iot_raw
    ports:
      - "8501:8501"
    restart: unless-stopped

volumes:
  mosquitto_data:
  influxdb_data: